image:
  file: .gitpod.dockerfile
ports:
  - port: 8070
tasks:
  - init: mvn install
vscode:
  extensions:
    - vscjava.vscode-java-pack@0.7.1:ea31zLwuaUsRabxq6oqI1w==
    - donjayamanne.git-extension-pack@0.1.3:SfFwfST7Hdp+r/KRulDGXA==
    - Pivotal.vscode-boot-dev-pack@0.0.8:BrfHu4se+ljgyUPUU+95ig==
    - vscjava.vscode-spring-boot-dashboard@0.1.6:/G6fobfzYSrYZdNU7UB78g==